[JIP-47-카드-컴포넌트] 카드 컴포넌트 구현
leanhaja/jipangs-client pull request #27
Opened 2023-02-24 15:04 UTC by jkpark104

# PR

## 🗄️ 종류

PR 종류를 선택하세요

- [x] Code Review
- [x] New Feature
- [ ] Remove Feature
- [ ] Change Logic
- [ ] Bug Fix
- [ ] Setup

<br>

## 🔍 왜 변경을 했습니까?

-

<br>

## 🔧 작업 내용

- 카드 컴포넌트 구현

<br>

## 📷 스크린샷

<br>

## 📝 리뷰할 때 참고할 점

-

2023-02-25 05:01 UTC, BHyeonKim requested changes

2023-02-25 05:01 UTC, BHyeonKim commented on apps/web/src/components/card/styled.tsx
> +  width: 100%;
overflow:hidden이 없어서 border-radius: 8px가 적용이 안되고 있습니다.
<img width="435" alt="스크린샷 2023-02-25 오후 1 32 47" src="https://user-images.githubusercontent.com/46583212/221338377-119debd4-2b79-4101-8b98-92b50b8d8ba8.png">

2023-02-25 05:01 UTC, BHyeonKim commented on apps/web/src/components/card/styled.tsx
> +  border-radius: 8px 8px 0 0;
figure의 하단 좌우 모서리를 둥글게 하려고 하신 것 같습니다!
하지만 상단 좌우 값을 둥글게 하신 것 같아요!
<img width="489" alt="스크린샷 2023-02-25 오후 1 31 49" src="https://user-images.githubusercontent.com/46583212/221338300-0f69b4dd-2213-4ca4-9583-8e15c4cae4fe.png">

2023-02-25 05:01 UTC, BHyeonKim commented on apps/web/src/components/card/styled.tsx
> +  width: 40px; */
이부분은 주석 처리가 왜 되있을까요? 🧐

2023-02-25 05:01 UTC, BHyeonKim commented on apps/web/src/components/card/index.tsx
> +          </Styled.TagList>
뭔가 오른쪽 태그와 왼쪽태그는 코드를 분리해야하지 않을까 고민됩니다.
실수로라도 3개 이상의 태그를 주었을때
<img width="373" alt="스크린샷 2023-02-25 오후 1 39 44" src="https://user-images.githubusercontent.com/46583212/221338771-ee2b8446-d3fa-4218-a40e-24e29635c263.png">
이렇게 되버리는 사태가 일어날 수 있어서요...

2023-02-25 05:01 UTC, BHyeonKim commented on apps/web/src/components/card/styled.tsx
> +  padding: 0 16px 10px;
기획안 디자인에서는 좌우 패딩이 없는 것 같습니다.
<img width="365" alt="스크린샷 2023-02-25 오후 1 51 33" src="https://user-images.githubusercontent.com/46583212/221338948-99b665a1-3efc-4d6a-a26d-e89be24b0d21.png">

2023-02-25 05:01 UTC, BHyeonKim commented on apps/web/src/components/card/styled.tsx
> +  aspect-ratio: 1.6 / 1;
비율은 왜 16:10으로 하셨을까요?🧐

2023-02-25 11:14 UTC, BHyeonKim commented on apps/web/src/components/card/index.tsx
> +          </Styled.TagList>
앗 이제 확인하니깐 카드 컴포넌트가 2개였군요... 햇갈렸습니다.

2023-02-26 12:04 UTC, merged

2023-02-26 12:05 UTC, jkpark104 commented
혹 이거 디자인시스템 만들기 전에 임시로 만들어놓은건데 그대로 올렸네요 수정해서 다시 올리겠습니다.

2023-02-26 12:06 UTC, jkpark104 commented on apps/web/src/components/card/index.tsx
> +          </Styled.TagList>
음.. 그래도 튜플로 처리하면 더 좋을 것 같습니다 감사해요 👍